### ISSUE TITLE
Adpater stürzt ab

### ISSUE THREAD

**Issue by myghost77** [ioBroker/ioBroker.lcn#26]
Ich nutze aktuell v1.1.1 des LCN-Adapters im ioBroker. Leider stürzt der Adapter nach einigen Minuten ab. Ich kann ihn leider so nicht nutzen...

Seine letzten Lebenszeichen sind:
```
2023-10-29 15:50:28.493  - debug: lcn.0 (37788) [CONN] received: =M000152.ZT224000001
2023-10-29 15:50:28.494  - debug: lcn.0 (37788) [LCN][RECEIVED] EG Treppenhaus Küche (CMDS-UPP) - {"segment":0,"module":152,"type":"IR","serial":"24000001"}
2023-10-29 15:50:28.498  - error:  lcn.0 (37788) Unhandled promise rejection. This error originated either  by throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch().
2023-10-29 15:50:28.498  - error: lcn.0 (37788) unhandled promise rejection: undefined is not a valid state value
2023-10-29 15:50:28.500  - error: lcn.0 (37788) Error: undefined is not a valid state value
at Object.maybeCallbackWithError  (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/maybeCallback.js:35:17)
at AdapterClass._setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5439:49)
at AdapterClass.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5400:21)
at _0x28eb93. (/opt/iobroker/node_modules/iobroker.lcn/main.js:1:64695)
at _0x28eb93.emit (node:events:513:28)
at /opt/iobroker/node_modules/iobroker.lcn/main.js:1:130611
at Array.forEach ()
at _0x31c733. (/opt/iobroker/node_modules/iobroker.lcn/main.js:1:129798)
at _0x31c733.emit (node:events:513:28)
at _0x31c733._0x53b886 (/opt/iobroker/node_modules/iobroker.lcn/main.js:1:117793)
2023-10-29 15:50:28.500  - error: lcn.0 (37788) undefined is not a valid state value
2023-10-29 15:50:28.500  - error:  lcn.0 (37788) Unhandled promise rejection. This error originated either  by throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch().
2023-10-29 15:50:28.501  - error: lcn.0 (37788) unhandled promise rejection: undefined is not a valid state value
2023-10-29 15:50:28.501  - error: lcn.0 (37788) Error: undefined is not a valid state value
at Object.maybeCallbackWithError  (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/maybeCallback.js:35:17)
at AdapterClass._setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5439:49)
at AdapterClass.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5400:21)
at _0x28eb93. (/opt/iobroker/node_modules/iobroker.lcn/main.js:1:64768)
at _0x28eb93.emit (node:events:513:28)
at /opt/iobroker/node_modules/iobroker.lcn/main.js:1:130611
at Array.forEach ()
at _0x31c733. (/opt/iobroker/node_modules/iobroker.lcn/main.js:1:129798)
at _0x31c733.emit (node:events:513:28)
at _0x31c733._0x53b886 (/opt/iobroker/node_modules/iobroker.lcn/main.js:1:117793)
2023-10-29 15:50:28.501  - error: lcn.0 (37788) undefined is not a valid state value
2023-10-29 15:50:28.501  - error:  lcn.0 (37788) Unhandled promise rejection. This error originated either  by throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch().
2023-10-29 15:50:28.501  - error: lcn.0 (37788) unhandled promise rejection: undefined is not a valid state value
2023-10-29 15:50:28.502  - error: lcn.0 (37788) Error: undefined is not a valid state value
at Object.maybeCallbackWithError  (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/maybeCallback.js:35:17)
at AdapterClass._setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5439:49)
at AdapterClass.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5400:21)
at _0x28eb93. (/opt/iobroker/node_modules/iobroker.lcn/main.js:1:64847)
at _0x28eb93.emit (node:events:513:28)
at /opt/iobroker/node_modules/iobroker.lcn/main.js:1:130611
at Array.forEach ()
at _0x31c733. (/opt/iobroker/node_modules/iobroker.lcn/main.js:1:129798)
at _0x31c733.emit (node:events:513:28)
at _0x31c733._0x53b886 (/opt/iobroker/node_modules/iobroker.lcn/main.js:1:117793)
2023-10-29 15:50:28.502  - error: lcn.0 (37788) undefined is not a valid state value
2023-10-29 15:50:28.502  - error:  lcn.0 (37788) Unhandled promise rejection. This error originated either  by throwing inside of an async function without a catch block, or by  rejecting a promise which was not handled with .catch().
2023-10-29 15:50:28.502  - error: lcn.0 (37788) unhandled promise rejection: undefined is not a valid state value
2023-10-29 15:50:28.502  - error: lcn.0 (37788) Error: undefined is not a valid state value
at Object.maybeCallbackWithError  (/opt/iobroker/node_modules/@iobroker/js-controller-common/build/lib/common/maybeCallback.js:35:17)
at AdapterClass._setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5439:49)
at AdapterClass.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5400:21)
at _0x28eb93. (/opt/iobroker/node_modules/iobroker.lcn/main.js:1:64920)
at _0x28eb93.emit (node:events:513:28)
at /opt/iobroker/node_modules/iobroker.lcn/main.js:1:130611
at Array.forEach ()
at _0x31c733. (/opt/iobroker/node_modules/iobroker.lcn/main.js:1:129798)
at _0x31c733.emit (node:events:513:28)
at _0x31c733._0x53b886 (/opt/iobroker/node_modules/iobroker.lcn/main.js:1:117793)
2023-10-29 15:50:28.503  - error: lcn.0 (37788) undefined is not a valid state value
2023-10-29 15:50:28.512  - debug: lcn.0 (37788) [CONN] Changing state: READY => CONNECTING
2023-10-29 15:50:29.014  - info: lcn.0 (37788) terminating
2023-10-29 15:50:29.015  - warn: lcn.0 (37788) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-10-29 15:50:29.564  - error: host.iobroker instance system.adapter.lcn.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-10-29 15:50:29.565  - info: host.iobroker Restart adapter system.adapter.lcn.0 because enabled
2023-10-29 15:50:29.565  - warn: host.iobroker Do not restart adapter system.adapter.lcn.0 because restart loop detected
```

**Comment by GermanBluefox** [comment]
Please test the 1.1.7 version

**Comment by myghost77** [comment]
Ich habe es jetzt zwei Tage gestestet und es läuft immer noch ohne Fehler. Vielen Dank!
