### ISSUE TITLE
Fehler nach Admin- Update + Node.JS - Update

### ISSUE THREAD

**Issue by Sefina-DS** [ioBroker/ioBroker.lcn#29]
Hi zusammen,

Bei mir ein ähnliches Problem.
Ich habe alles heute auf dem neusten stand gebracht und nun geht der LCN Adapter nicht.
Anbei meine Logs ....

Leider bin ich noch auf den Adapter angewiesen.

```
host.IO-Broker | 2024-08-03 21:54:40.301 | info | Rebuild  for adapter system.adapter.lcn.0 not successful in 3 tries. Adapter  will not be restarted again. Please execute "npm install --production"  in adapter directory manually.
host.IO-Broker | 2024-08-03 21:54:40.301 | error | instance system.adapter.lcn.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]: Node.js v20.16.0
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]: }
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]:   requireStack: [ '/opt/iobroker/node_modules/iobroker.lcn/main.js' ]
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]:   code: 'MODULE_NOT_FOUND',
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]:     at _0x2b3b62 (/opt/iobroker/node_modules/iobroker.lcn/main.js:1:3919) {
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]:     at 7.fs (/opt/iobroker/node_modules/iobroker.lcn/main.js:1:151514)
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.lcn/main.js:1:151487)
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.lcn/main.js:1:151272)
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.lcn/main.js:1:4026
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]:     at _0x2b3b62 (/opt/iobroker/node_modules/iobroker.lcn/main.js:1:3613)
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]:     at require (node:internal/modules/helpers:179:18)
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]:     at Module.require (node:internal/modules/cjs/loader:1233:19)
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]:     at Module._load (node:internal/modules/cjs/loader:986:27)
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]:     at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]: - /opt/iobroker/node_modules/iobroker.lcn/main.js
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]: Require stack:
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]: Error: Cannot find module '/opt/iobroker/node_modules/iobroker.js-controller/build/lib/adapter.js'
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]:   ^
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]:   throw err;
host.IO-Broker | 2024-08-03 21:54:40.301 | error | Caught by controller[0]: node:internal/modules/cjs/loader:1148
host.IO-Broker | 2024-08-03 21:54:40.166 | info | instance system.adapter.lcn.0 in version "1.1.8" started with pid 817815
host.IO-Broker | 2024-08-03 21:54:39.965 | info | "system.adapter.lcn.0" enabled
host.IO-Broker | 2024-08-03 21:54:20.246 | info | "system.adapter.lcn.0" disabled

```

_Originally posted by @Sefina-DS in https://github.com/ioBroker/ioBroker.lcn/issues/28#issuecomment-2267119477_

**Comment by Apollon77** [comment]
duplicate #28
